module.exports = {
  rules: {
    'selector-list-comma-newline-after': ['always', { severity: 'warn' }],
    'block-no-empty': true,
    'function-comma-space-after': 'always',
    'function-name-case': 'lower',
    'number-leading-zero': 'never',
    'string-quotes': 'double',
    'length-zero-no-unit': true,
    'time-no-imperceptible': true,
    'unit-case': 'lower',
    'value-keyword-case': 'lower',
    'shorthand-property-no-redundant-values': true,
    'property-case': 'lower',
    'property-no-unknown': true,
    'declaration-colon-space-before': 'never',
    'declaration-block-no-duplicate-properties': true,
    'declaration-block-no-ignored-properties': true,
    'block-closing-brace-empty-line-before': 'never',
    'block-opening-brace-space-before': 'always',
    'selector-attribute-brackets-space-inside': 'never',
    'selector-type-case': 'lower',
    'selector-root-no-composition': true,
    'rule-nested-empty-line-before': 'always-multi-line',
    'comment-no-empty': true,
    'no-duplicate-selectors': true,
    'no-extra-semicolons': true,
    'no-invalid-double-slash-comments': true,
  },
};
